[general]
live_config_reload = true

[window]
padding = { x = 4, y = 5 }
decorations = "None"

[scrolling]
history = 2000

[font]
size = 12

[font.normal]
family = "Fira Code"

[font.bold]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[cursor]
blink_interval = 500
blink_timeout = 1

[cursor.style]
blinking = "On"

[bell]
duration = 0

# Catppuccin Mocha
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text   = "#1e1e2e"
cursor = "#f5e0dc"

[colors.selection]
text       = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#a6adc8"
